### ISSUE TITLE
指针类型问题

### ISSUE THREAD

**Issue by Logic-Bai** [netube99/RingBuffer#1]
你好 开发者：
我在使用过程中发现了你代码中的一点小问题
![image](https://user-images.githubusercontent.com/45715098/118079056-f12de200-b3e9-11eb-9ebb-662bd716f2fd.png)
这个函数（我私自修改了函数名，但是注释没有修改）中的
![image](https://user-images.githubusercontent.com/45715098/118079097-14f12800-b3ea-11eb-946a-bc4c83aff0fc.png)
这个指针没有设置指针的类型，在我的MDK 5中编译无法通过，我为其强制转换了类型才可以编译通过

**Comment by netube99** [comment]
谢谢反馈
我有空会测试一下这个问题，我用mingw64和MDK Compiler 6都可以编译通过
但确实这里不转换成uint8_t的确会不明确地址长度，你修改的方法是正确的
